app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/', views.logout, name='logout'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/delete/', views.delete, name='delete'),
    path('accounts/update/', views.update, name='update'),

    path('', views.Main.as_view()),
    path('list/', views.List.as_view()),
    path('mypage/', views.Mypage.as_view(), name='mypage'),
    path('friends/', views.Friends.as_view()),
    
    path('add_friend/<str:friend_username>/', views.AddFriendView.as_view(), name='add_friend'),
    path('add_my_like/<str:my_like_username>/', views.Addmy_likeView.as_view(), name='add_my_like'),
    # path('add_you_liked/<str:you_liked_username>/', views.Addyou_likedView.as_view(), name='add_you_liked'),
    
    path('remove_friend/<str:friend_username>/', views.RemoveFriendView.as_view(), name='remove_friend'),
    path('remove_my_like/<str:my_like_username>/', views.Removemy_likeView.as_view(), name='remove_my_like'),
    path('remove_you_liked/<str:you_liked_username>/', views.Removeyou_likedView.as_view(), name='remove_you_liked'),
    
    path('auto_match_friends/', views.auto_match_friends, name='auto_match_friends'),

    path('board/post_list/', views.PostList.as_view()),
    path('board/<int:pk>/', views.PostDetail.as_view()),
    path('board/create_post/', views.PostCreate.as_view()),
    path('board/update_post/<int:pk>', views.PostUpdate.as_view()),

    path('comment_create/<int:pk>', views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),

    path('list/list_search/', views.list_search, name='list_search'),
    path('post_search/', views.post_search, name='post_search'),
]

dukonnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/board/post_detail.html
{% extends 'module/base.html' %}

{% block title %}게시물{% endblock %}
{% block content %}
<div>
    <div class="mb-4 bg-light py-2 px-2 border-b-2">
        <p class="flex justify-between mb-0 ">
            <b class="text-lg">제목: {{post.title}}</b>
            <span>
                {{post.author}}
                ({{post.create_at | date:"Y-m-d"}})

                <span>
                    <a href="/board/update_post/{{ post.pk }}" class="no-underline px-2 py-1  rounded bg-pink text-white ml-3">수정하기</a>
                </span>
            </span>
        </p>
    </div>


    {% if post.image %}
        <figure class="mb-4">
            <img class="img-fluid rounded" src="{{ post.image.url }}"  />
        </figure>
    {% endif %}


    <div>
        <p class="text-base p-3">{{ post.content }}</p>
    </div>

    {% if post.file_upload %}
        <a href="{{ post.file_upload.url }}" class="btn btn-outline-dark" role="button" download>Download</a>
    {% endif %}

    <div class="comment"> 
        <!-- 댓글 폼 표시 -->
        <b class="w-full bg-light py-2 border-t-2 border-b-2 block">댓글 작성</b>
        <form method="post" action="{% url 'app:comment_create'  pk=post.pk  %}">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="bg-[#FF176A] text-white px-2">댓글 작성</button>
        </form>
    
        
        <!-- 댓글 목록 표시 -->
        <b class="w-full bg-light py-2 border-t-2 border-b-2 block mt-3">댓글</b>
        <ul class="pl-0">
            {% for comment in comments  %}
                <li class="flex border-b-[1px]  py-1">
                    <b class="mr-2">{{ comment.author }}</b>
                    <p class="m-0">{{ comment.content }}</p>
                    <small class="ml-auto">
                        {{ comment.create_at | date:"Y-m-d h:m" }}
                        <form method="post" action="{% url 'app:delete_comment' comment.id %}" class="inline-block ml-1">
                            {% csrf_token %}
                            <button type="submit" class="shadow-none text-sm text-red-500">삭제</button>
                        </form>
                    </small>
                </li>
            {% endfor %}
        </ul>

    </div>



</div>
{% endblock %}

app/templates/board/post_form.html
{% extends 'module/md_base.html' %}
{% block title %}새 글 작성하기{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button type="submit" class="pink px-5 my-4 text-white mx-auto block h-[50px]">작성하기</button>
</form>

{%  endblock   %}

app/templates/board/post_list.html
{% extends 'module/base.html' %}
{% block title %}자유게시판{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <a href="/board/create_post/" class="bg-pink text-white px-2 py-1 rounded no-underline right-7 top-[30px] block absolute">
        새 글 작성하기
    </a>
{% endif %}

<div class="mb-3">
    <form class="flex " method="GET" action="{% url 'app:post_search' %}">
        <div class="input-group">
          <input type="text" class="form-control rounded m-0 mr-2" placeholder="검색" aria-label="검색" name="q" value="{{ query }}">
          <button class="bg-[#FF176A] text-white shadow-none h-full px-3 mx-2 rounded" type="submit" id="button-addon2">검색</button>
          {% if query %}
            <a href="/board/post_list/" class="no-underline border-1 rounded shadow-none  px-3 h-full bg-blue-800 text-white pt-2">
             초기화
            </a>
          {% endif %}
        </div>
      </form>



  </div>

  {% if post_list.exists %}
    <table class="post-list">
      <thead>
        <tr>
          <th>No</th>
          <th>제목</th>
          <th>작성 날짜</th>
          <th>작성자</th>
        </tr>
      </thead>
      <tbody>
        {% for p in post_list %}
          <tr>
            <td>{{ p.pk }}</td>
            <td>
              <a href="{{ p.get_absolute_url }}" class="no-underline text-[#333]">
                {{ p.title }}
              </a>
            </td>
            <td>{{ p.create_at | date:"Y-m-d" }}</td>
            <td>{{ p.author }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <p class="text-pink-500 text-2xl text-center mt-20">게시물이 없습니다</p>
  {% endif %}
{% endblock %}

app/templates/board/post_update_form.html
{% extends 'module/md_base.html' %}

{% block title %}게시글 수정{% endblock %}

{% block content %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{form}}
    </table>
    <button type="submit" class="pink px-5 my-4 text-white mx-auto block h-[50px]">작성하기</button>
</form>

{%  endblock   %}