app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/', views.logout, name='logout'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/delete/', views.delete, name='delete'),
    path('accounts/update/', views.update, name='update'),

    path('', views.Main.as_view()),
    path('list/', views.List.as_view()),
    path('mypage/', views.Mypage.as_view(), name='mypage'),
    path('friends/', views.Friends.as_view()),
    
    path('add_friend/<str:friend_username>/', views.AddFriendView.as_view(), name='add_friend'),
    path('add_my_like/<str:my_like_username>/', views.Addmy_likeView.as_view(), name='add_my_like'),
    # path('add_you_liked/<str:you_liked_username>/', views.Addyou_likedView.as_view(), name='add_you_liked'),
    
    path('remove_friend/<str:friend_username>/', views.RemoveFriendView.as_view(), name='remove_friend'),
    path('remove_my_like/<str:my_like_username>/', views.Removemy_likeView.as_view(), name='remove_my_like'),
    path('remove_you_liked/<str:you_liked_username>/', views.Removeyou_likedView.as_view(), name='remove_you_liked'),
    
    path('auto_match_friends/', views.auto_match_friends, name='auto_match_friends'),

    path('board/post_list/', views.PostList.as_view()),
    path('board/<int:pk>/', views.PostDetail.as_view()),
    path('board/create_post/', views.PostCreate.as_view()),
    path('board/update_post/<int:pk>', views.PostUpdate.as_view()),

    path('comment_create/<int:pk>', views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),

    path('list/list_search/', views.list_search, name='list_search'),
    path('post_search/', views.post_search, name='post_search'),
]

dukonnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/accounts/login.html
{% extends 'module/sm_base.html' %}
{% block title %}로그인{% endblock %}

{% block content %}
<form method="post" action="{% url 'app:login' %}">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="pink acc-btn">로그인</button>
</form>
<div class="mt-5 ">
    <a href="/accounts/signup">
        <u class="underline text-sm">계정이 없으신가요?</u>
    </a>
</div>
{% endblock %}

app/templates/accounts/signup.html
{% extends 'module/sm_base.html' %}
{% block title %}회원가입{% endblock %}

{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'app:signup' %}" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="pink acc-btn">생성하기</button>
    </form>
</div>

{% endblock %}

app/templates/accounts/update.html
{% extends 'module/sm_base.html' %}
{% block title %}내 정보 수정{% endblock %}

{% block content %}
    <form method="POST" action="{% url 'app:update' %}">

        {% csrf_token %}
        {{form.as_p}}

        <button type="submit" class="pink acc-btn">수정하기</button>
        
      </div>
    </form>
{% endblock %}