app/urls.py
from django.urls import path
from . import views

app_name = 'app'
urlpatterns = [
    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/', views.logout, name='logout'),
    path('accounts/signup/', views.signup, name='signup'),
    path('accounts/delete/', views.delete, name='delete'),
    path('accounts/update/', views.update, name='update'),

    path('', views.Main.as_view()),
    path('list/', views.List.as_view()),
    path('mypage/', views.Mypage.as_view(), name='mypage'),
    path('friends/', views.Friends.as_view()),
    
    path('add_friend/<str:friend_username>/', views.AddFriendView.as_view(), name='add_friend'),
    path('add_my_like/<str:my_like_username>/', views.Addmy_likeView.as_view(), name='add_my_like'),
    # path('add_you_liked/<str:you_liked_username>/', views.Addyou_likedView.as_view(), name='add_you_liked'),
    
    path('remove_friend/<str:friend_username>/', views.RemoveFriendView.as_view(), name='remove_friend'),
    path('remove_my_like/<str:my_like_username>/', views.Removemy_likeView.as_view(), name='remove_my_like'),
    path('remove_you_liked/<str:you_liked_username>/', views.Removeyou_likedView.as_view(), name='remove_you_liked'),
    
    path('auto_match_friends/', views.auto_match_friends, name='auto_match_friends'),

    path('board/post_list/', views.PostList.as_view()),
    path('board/<int:pk>/', views.PostDetail.as_view()),
    path('board/create_post/', views.PostCreate.as_view()),
    path('board/update_post/<int:pk>', views.PostUpdate.as_view()),

    path('comment_create/<int:pk>', views.comment_create, name='comment_create'),
    path('comment/delete/<int:comment_id>/', views.delete_comment, name='delete_comment'),

    path('list/list_search/', views.list_search, name='list_search'),
    path('post_search/', views.post_search, name='post_search'),
]

dukonnect/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/templates/auto_match_friends.html
{% extends 'module/base.html' %}
{% load static %}
{% block title %}친구 자동 매칭 결과{% endblock %}

{% block content %}
  <div class="flex justify-start items-start flex-wrap">
    {% for match in matched_friends %}
      <div class="border-1 p-0 mb-5 w-[32%] rounded overflow-hidden mr-[10px]">
        <div class="h-[200px] overflow-hidden flex justify-center items-center">
          {% if match.friend.back_image %}
            <img class="card-img-top" src="{{ match.friend.back_image.url }}" alt="default image">
          {% else %}
            <img class="card-img-top" src="{% static 'images/profile/back.png' %}" alt="default image">
          {% endif %}
        </div>

        <div class="min-h-[300px] p-3">
          <h5 class="flex items-center">
            {% if match.friend.prof_image %}
              <img src="{{ match.friend.prof_image.url }}" alt="프로필 사진" class="w-[50px] h-[50px] mr-3">
            {% else %}
              <img class="card-img-top" src="{% static 'images/profile/prof.png' %}" alt="default image">
            {% endif %}
            {{ match.friend.nickname }}
          </h5>
          <p class="card-text">{{ match.friend.major1 }} | {{ match.friend.major2 }}</p>
          {% for tag in match.common_tags %}
            <div class="bg-slate-100 rounded-2xl px-3 py-1 break-keep inline-block mt-1 mr-1 text-sm">#{{ tag.name }}</div>
          {% endfor %}
          <div>
            <button class="pink px-2 block mt-5 px-3">
              <a href="/add_my_like/{{match.friend.username}}/" class="text-white hover:text-white no-underline">
                친구요청하기
              </a>

            </button>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

app/templates/friends.html
{% extends 'module/base.html' %}

{% block title %}내 친구{% endblock %}

{% block content %}

<ul role="list" class="divide-y divide-gray-100">
  {%if friends_users or my_like_users or you_liked_users %}
    {% if my_like_users %}
    {% for f in my_like_users %}
  
      <li class="flex justify-between gap-x-6 border-1 p-3 mb-2 hover:bg-gray-50 rounded">
        <div class="flex min-w-0 gap-x-4 w-full">
          <img class="h-[100px] w-[100px] flex-none rounded-full bg-gray-50" src="{{ f.prof_image.url }}">

          <div class="flex-auto w-full">
            <b class="text-lg text-gray-900 mb-1 block w-full flex justify-between">
              {{f.name}}
              <div>
                <a class="inline-block ml-auto bg-gray-100 no-underline text-[#333] hover:bg-gray-200 px-2 border-2 rounded">수락 대기 중</a>
                <a href="/remove_my_like/{{f.username}}" class="inline-block ml-auto bg-gray-100 no-underline text-[#333] hover:bg-gray-200 px-2 border-2 rounded bg-red-500 hover:bg-red-500 text-white hover:text-white border-red-500">삭제</a>
              </div>
            </b>
            <p class="mb-2">
              {{f.major1}} |  {{f.major2}} <br>
              {{f.birth | date:"Y-m-d" }}<br>
              
            </p>
            <div>

              {% if f.tag.exists %}
                {% for tag in f.tag.all %}
                <span class="bg-pink rounded-2xl px-3 py-1 text-white break-keep inline-block mt-1 mr-1">{{tag}}</span>
                {% endfor %}
              {% endif %}
            </div>
     
          </div>
        </div>
   
      </li>
    {% endfor %}
    {% endif %}

    {% if you_liked_users %}
    {% for f in you_liked_users %}
  
      <li class="flex justify-between gap-x-6 border-1 p-3 mb-2 hover:bg-gray-50 rounded">
        <div class="flex min-w-0 gap-x-4 w-full">
          <img class="h-[100px] w-[100px] flex-none rounded-full bg-gray-50" src="{{ f.prof_image.url }}">

          <div class="flex-auto w-full">
            <b class="text-lg text-gray-900 mb-1 block w-full flex justify-between">
              {{f.name}}
              <div>
                <a href="/add_friend/{{f.username}}" class="inline-block ml-auto bg-gray-100 no-underline text-[#333] hover:bg-red-500 px-2 border-2 rounded ml-auto bg-red-500 text-white border-0">수락</a>
                <a href="/remove_you_liked/{{f.username}}" class="inline-block ml-auto no-underline px-2 border-2 rounded bg-blue-700 text-white border-0">거절</a>
              </div>
            </b>
            <p class="mb-2">
              {{f.major1}} |  {{f.major2}} <br>
              {{f.birth | date:"Y-m-d" }}<br>
              
            </p>
            <div>

              {% if f.tag.exists %}
                {% for tag in f.tag.all %}
                <span class="bg-pink rounded-2xl px-3 py-1 text-white break-keep inline-block mt-1 mr-1">{{tag}}</span>
                {% endfor %}
              {% endif %}
            </div>
     
          </div>
        </div>
   
      </li>

    {% endfor %}
    {% endif %}

    {% if friends_users %}
    {% for f in friends_users %}
  
      <li class="flex justify-between gap-x-6 border-1 p-3 mb-2 hover:bg-gray-50 rounded">
        <div class="flex min-w-0 gap-x-4 w-full">
          <img class="h-[100px] w-[100px] flex-none rounded-full bg-gray-50" src="{{ f.prof_image.url }}">

          <div class="flex-auto w-full">
            <b class="text-lg text-gray-900 mb-1 block w-full flex">
              {{f.name}} ({{f.tel }})
              <a href="/remove_friend/{{f.username}}" class="inline-block ml-auto bg-gray-100 no-underline text-[#333] hover:bg-gray-200 px-2 border-2 rounded">삭제</a>
            </b>
            <p class="mb-2">
              {{f.major1}} |  {{f.major2}} <br>
              {{f.birth | date:"Y-m-d" }}<br>
              
            </p>
            <div>

              {% if f.tag.exists %}
                {% for tag in f.tag.all %}
                <span class="bg-pink rounded-2xl px-3 py-1 text-white break-keep inline-block mt-1 mr-1">{{tag}}</span>
                {% endfor %}
              {% endif %}
            </div>
     
          </div>
        </div>
   
      </li>

    {% endfor %}
    {% endif %}

    {% else %}
     <p class="text-pink-500 text-2xl text-center mt-20">
      아직 매칭 된 친구가 없습니다<br>
      <a href="/list" class="underline text-sm text-pink-500 mt-5">친구들 만나러 가기</a>
     </p>
    {% endif %}

  </ul>




{% endblock %}

app/templates/list.html
{% extends 'module/base.html' %}
{% load static %}

{% block title %}공개구벗{% endblock %}

{% block content %}
  <div class="mb-3 h-10">
    <form class="flex " method="GET" action="{% url 'app:list_search' %}">
      <div class="input-group">
        <input type="text" class="form-control rounded m-0 mr-2" placeholder="검색" aria-label="검색" name="q" value="{{ query }}">
        <button class="bg-[#FF176A] text-white shadow-none h-full px-3 mx-2 rounded" type="submit" id="button-addon2">검색</button>
        {% if query %}
          <a href="/list" class=" no-underline">
            <button class="border-1 rounded shadow-none  px-3 h-full bg-blue-800 text-white">
              초기화
            </button>
          </a>
        {% endif %}
      </div>
    </form>
  </div>

  <div class="flex justify-start items-start flex-wrap">
    {% for m in object_list %}
      {% if m != request.user and m.username != "admin" %}
        <div class="border-1 p-0 mb-5 w-[31%] rounded overflow-hidden m-[1%]">
          <div class="h-[200px] overflow-hidden flex justify-center items-center">
            {% if m.back_image %}
              <img class="card-img-top" src="{{ m.back_image.url }}" alt="default image">
            {% else %}
              <img class="card-img-top" src="{% static 'images/profile/back.png' %}" alt="default image">
            {% endif %}
          </div>
          <div class="min-h-[300px] p-3 flex flex-col">
            <h5 class="flex  items-center"> 
              <div class="w-[50px] h-[50px] mr-3 rounded-[50%] overflow-hidden">
                {% if m.prof_image %}
                  <img src="{{ m.prof_image.url }}" alt="프로필 사진"  class="w-full"> 
                {% else %}
                  <img src="{% static 'images/profile/prof.png' %}" alt="default image" class="w-full">
                {% endif %}
              </div>
              {{ m.nickname }}
            </h5>
            <p class="card-text">{{ m.major1 }} | {{ m.major2 }}</p>
            <div>
              {% for t in m.tag.all %}
                <div class="bg-slate-100 rounded-2xl px-3 py-1 break-keep inline-block mt-1 mr-1 text-sm">#{{t.name}}</div>
              {% endfor %}
            </div>
            <button class="pink px-2 block mt-auto px-3">
              <a href="/add_my_like/{{m.username}}/" class="text-white hover:text-white no-underline">
                친구요청하기
              </a>
            </button>
          </div>
        </div>
      {% endif %}
    {% endfor %}

    {% if not object_list and not query %}
      <p>공개된 프로필이 없습니다.</p>
    {% elif not object_list %}
      <p>검색 결과가 없습니다.</p>
    {% endif %}
  </div>
{% endblock %}

app/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>DUKONNECT</title>
    
    <!-- css load -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" media="screen">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css" />
    <link rel="stylesheet" href="{% static 'css/common.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/main.css' %}" media="screen">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    {% include 'module/navbar.html' %}
    <div class="swiper mySwiper">
        <div class="swiper-wrapper">
            <div class="swiper-slide section1">
                <div class="container mt-[150px] h-[80vh]">
                    <div class="row" >
                        <div class="flex justify-between items-center mb-4">
                            <div class="w-[43%]">
                                <h2 class="font-bold text-4xl mb-3">
                                    즐거운 학교생활 !<br>
                                    추억을 공유 할 친구 사귀기 !
                                </h2>
                                <p class="text-lg mb-5">
                                    우리 학교에서 새로운 친구를 사귀고 싶을 때<br>
                                    덕커넥트를 통해 관심사가 비슷한 친구를 사귀어요 !
                                </p>
                                {% if user.is_authenticated %}
                                <a href="/mypage" class="text-[#FF176A] hover:text-white hover:bg-[#FF176A] border-1 border-[#FF176A] no-underline px-4 py-2">
                                    시작하기
                                </a>
                                {% else %}
                                <a href="/accounts/login" class="text-[#FF176A] hover:text-white hover:bg-[#FF176A] border-1 border-[#FF176A] no-underline px-4 py-2">
                                    시작하기
                                </a>
                                {% endif %}
                            </div>
                            <div  class="w-[43%]">
                                <img src="{% static 'images/homepage/main/school.png' %}">
                            </div>
                        </div>
        
                        <div class="card">
                            <b class="text-xl mt-[10px] pl-[20px]">덕커넥트 이용방법</b>
                            <ul class="flex justify-between items-center step">
                                <li>
                                    <b >STEP1</b>
                                    <p>[내 정보]에서 나의 정보를 입력해요. 이 정보를 바탕으로 친구를 매칭해요.</p>
                                </li>
                                <div class="border-1 h-full "></div>
                                <li>
                                    <b >STEP2</b>
                                    <p>[내 친구]에서 [자동 매칭 시작하기]를 선택해요. 매칭이 완료되면 서로의 전화번호가 공유돼요.</p>
                                </li>
                                <div class="border-1 h-full "></div>
                                <li>
                                    <b >STEP3</b>
                                    <p>더욱 다양하고 많은 친구를 만나고 싶을 땐 [내 정보]에서 [공개구친]에 체크해요.</p>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide section2">
                <div class="container  mt-[150px] h-[80vh]">
                    <div class="row" >
                        <h3 class="font-bold text-4xl text-center">
                            즐거운 학교생활 !<br>
                            추억을 공유 할 친구 사귀기 !
                        </h3>
                        <div class="flex justify-between items-center mb-5">
                            <div class="w-[40%] center flex-col">
                                <img src="{% static 'images/homepage/main/girl1.png' %}" class="w-[60%] mb-3">

                                <div class="card text-lg p-4">
                                    덕커넥트 ! 나만의 음식 취향 🍕<br>
                                    나의 최애 아이돌🤹‍♂️  내가 요즘 빠져버린 게임 🎯<br>
                                    <span class="mt-3 text-lg">
                                        같이 즐길 친구를 찾아줘~!
                                    </span>
                                </div>
                            </div>
                            <div class="w-[60%]">
                                <div class="talk-pink">
                                    전공이 나와 같은 사람을 만나<br>
                                    함께 공부하고싶어!
                                </div>
                                <div class="talk-pink">
                                    난 중국음식 매니아인데, 같이 <br>
                                    먹으러 갈 친구가 있으면 좋겠어!
                                </div>
                                <div class="talk-pink">
                                    닌텐도 같이 할 사람 ~ !<br>
                                    나는 동물의 숲 고인물이야~
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide section3">
                <div class="container  mt-[150px] h-[80vh]">
                    <div class="row" >
                        <h4 class="font-bold text-4xl text-left mb-3">
                            친구를 찾아보자 !
                        </h4>
                        <p class="mb-5 text-lg">
                            우리 학교에서 새로운 친구를 사귀고 싶을 때<br>
                            덕커넥트를 통해 관심사가 비슷한 친구를 사귀어요 !
                        </p>

                        <div class="flex justify-between">
                            <div class="card p-0 w-[31%]">
                                <div class="icon bg-semigray center flex-col py-3 h-[250px]">
                                    <img src="{% static 'images/homepage/main/icon1.png' %}" >
                                    <b class="text-2xl font-bold mt-4">내 정보 입력</b>
                                </div>
                                <div class="p-3 flex flex-col justify-between h-auto">
                                    <p class="text-lg">
                                        나에 대한 전공과 취향을 입력하고 만나고 싶은 친구의 전공과 취향도 함께 입력해요!
                                    </p>
                                    {% if user.is_authenticated %}
                                    <a href="/mypage" class="text-[#FF176A] hover:text-[#FF176A]">바로가기  →</a>
                                    {% else %}
                                    <a href="/accounts/login" class="text-[#FF176A] hover:text-[#FF176A]">바로가기  →</a>
                                    {% endif %}
                                   
                                </div>
                            </div>
                            <div class="card p-0 w-[31%]">
                                <div class="icon  bg-pink center flex-col py-3 h-[250px]">
                                    <img src="{% static 'images/homepage/main/icon2.png' %}" >
                                    <b class="text-2xl font-bold mt-4 text-white">자동 맞춤 매칭</b>
                                </div>
                                <div class="p-3 flex flex-col justify-between h-auto">
                                    <p class="text-lg">
                                        내 정보를 바탕으로 키워드가 겹치는 친구를 찾아서 추천해줘요!
                                    </p>
                                    {% if user.is_authenticated %}
                                    <a href="/mypage" class="text-[#FF176A] hover:text-[#FF176A]">바로가기  →</a>
                                    {% else %}
                                    <a href="/accounts/login" class="text-[#FF176A] hover:text-[#FF176A]">바로가기  →</a>
                                    {% endif %}
                                </div>
                            </div>
                            <div class="card p-0 w-[31%]">
                                <div class="icon bg-yellow center flex-col py-3 h-[250px]">
                                    <img src="{% static 'images/homepage/main/icon3.png' %}" >
                                    <b class="text-2xl font-bold mt-4 text-white">공개 구친</b>
                                </div>
                                <div class="p-3 flex flex-col justify-between h-auto">
                                    <p class="text-lg">
                                        더욱 다양하고 많은 친구를 만나보고 싶을
                                        땐 나의 프로필을 공개하여 공개구친에
                                        참여해요!
                                    </p>
                                    <a href="/list" class="text-[#FF176A] hover:text-[#FF176A]">바로가기  →</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="swiper-slide section4">
                <div class="container  mt-[150px] h-[80vh]">
                    <div class="row" >
                        <h5 class="font-bold text-4xl text-left mb-3">
                            지금도 많은 친구들이<br>
                            기다리고 있어요!
                        </h5>
                        <a href="/list" class="text-[#FF176A] hover:text-[#FF176A] mb-5 hover:text-[#FF176A] hover:text-[#FF176A]">더 많은 친구들 만나러 가기  →</a>

                        <div class="friends-list w-full">
                            <div class="swiper friendsSwiper">
                                <div class="swiper-wrapper">
                                    {% for m in object_list %} 
                                        {% if m != request.user and m.username != "admin" %}
                                        <div class="swiper-slide">
                                            <div class="card p-0 mb-5">
                                                <div class="h-[200px] overflow-hidden flex justify-center items-center mb-2">
                                                    {% if m.back_image %}
                                                        <img class="card-img-top" src="{{ m.back_image.url }}" alt="default image">
                                                    {% else %}
                                                        <img class="card-img-top" src="{% static 'images/profile/back.png' %}" alt="default image">
                                                    {% endif %}
                                                </div>
                                        
                                                
                                                <div class="card-body h-[230px]">
                                                    <div class="flex  items-center">
                                                        <div  class="w-[50px] h-[50px] mr-3 rounded-[50%] overflow-hidden">
                                                            {% if m.prof_image %}
                                                            <img src="{{ m.prof_image.url }}" alt="프로필 사진" class="w-full"> 
                                                            {% else %}
                                                            <img src="{% static 'images/profile/prof.png' %}" alt="default image" class="w-full">
                                                            {% endif %}
                                                        </div>
                                                        <h5 class="card-title"> 
                                                            {{ m.name }}
                                                        </h5>
                                                    </div>
                                                    <p class="card-text">{{ m.major1 }} | {{ m.major2 }}</p>
                                                    {% for t in m.tag.all %}
                                                    <div class="bg-slate-100 rounded-2xl px-3 py-1 break-keep inline-block mt-1 mr-1 text-sm">#{{t.name}}</div>
                                                    {% endfor %}
                                                </div>
                                            </div>  
                                        </div>  
                                        {% endif %}
                                    {% endfor %}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
        <div class="swiper-pagination"></div>
      </div>

    <!-- js load -->

    <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

app/templates/mypage.html
{% extends 'module/sm_base.html' %}
{% load static %}
{% block title %}내 정보{% endblock %}
{% block content %}
    <div class="w-full h-[200px] overflow-hidden">
        {% if object.back_image %}
            <img src="{{ object.back_image.url }}" alt="배경 사진" class="w-full "> 
        {% else %}
            <img src="{% static 'images/profile/back.png' %}"  class="w-full ">
        {% endif %}
    </div>


    <div class="w-40 h-40 overflow-hidden rounded-[50%] z-1 block  mt-[-7rem] mx-auto">

        {% if object.prof_image %}
        <img src="{{ object.prof_image.url }}" alt="프로필 사진" class="w-full"> 
        {% else %}
        <img src="{% static 'images/profile/prof.png' %}" class="w-full" >
        {% endif %}
    </div>
    <div class="info mt-3">
        <ul class="p-0">
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">이름</b>
                {{ object.name }} ({{ object.studentID}})
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">닉네임</b> 
                {{ object.nickname }}
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">ID</b> 
                {{ object.username }}
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">이메일</b> 
                {{ object.email }}
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">생년월일</b>
                {{ object.birth | date:"Y-m-d"  }}
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">연락처</b>
                {{ object.tel }}
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">제1전공</b>
                {{ object.major1 }}
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">제2전공</b>
                {{ object.major2 }}
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">해시태그</b>
                <ul class="p-0 flex flex-wrap">
                    {% for t in object.tag.all %}
                    <li class="bg-slate-100 block rounded-3xl mr-2 px-2 py-1 mb-1">#{{t.name}}</li>
                    {% endfor %}
                </ul>
            </li>
            <li class="flex min-h-[1.75rem]">
                <b class="min-w-[110px] block">프로필 공개</b>
                {% if object.open_profile %}
                공개 중
                {% else %}
                비공개
                {% endif%}
            </li>
        </ul>
    </div>

    <button class="pink px-3 rounded mr-1 w-full h-[50px] mt-3">
        <a href="{% url 'app:auto_match_friends' %}" class="text-white hover:text-white no-underline">친구 자동 매칭</a>
    </button>
    <div class="flex justify-between mt-2">
        <a href="/accounts/update" class="w-[48%] block">
            <button class="bg-gray-100 text-gray-500 hover:text-gray-800 px-3 roundedinline-block mr-1 w-full h-[50px]">수정하기</button>
        </a>
        <a href="/accounts/delete" class="w-[48%] block">
            <button class="bg-gray-100 text-gray-500 hover:text-gray-800 px-3 roundedinline-block w-full h-[50px]">탈퇴하기</button>
        </a>
    </div>
 
{% endblock %}